// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJIO75WEj5JyVwMy8Ru33KneZLtik-95o',
    appId: '1:1045029044825:web:5f7a7e8bd4be71c5b2e748',
    messagingSenderId: '1045029044825',
    projectId: 'flutterforwardextended',
    authDomain: 'flutterforwardextended.firebaseapp.com',
    storageBucket: 'flutterforwardextended.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTj1r1Pn1BapbNLQnoPo07eiYtafjTRk',
    appId: '1:1045029044825:android:8dfc073d68facefeb2e748',
    messagingSenderId: '1045029044825',
    projectId: 'flutterforwardextended',
    storageBucket: 'flutterforwardextended.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbqwXqH5kJMGEm0cCCSlb4XRHrdzEhv0',
    appId: '1:1045029044825:ios:ab58bbfd69ec0a15b2e748',
    messagingSenderId: '1045029044825',
    projectId: 'flutterforwardextended',
    storageBucket: 'flutterforwardextended.appspot.com',
    iosClientId: '1045029044825-hgiqk6j8oa6v7ri7jag0k07tl382oj7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbqwXqH5kJMGEm0cCCSlb4XRHrdzEhv0',
    appId: '1:1045029044825:ios:ab58bbfd69ec0a15b2e748',
    messagingSenderId: '1045029044825',
    projectId: 'flutterforwardextended',
    storageBucket: 'flutterforwardextended.appspot.com',
    iosClientId: '1045029044825-hgiqk6j8oa6v7ri7jag0k07tl382oj7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled101',
  );
}
